name: dart_playground
description: A playgound to learn dart
version: 1.0.0

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  stomp_dart_client: ^0.3.8

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.0.0

